export const REQUEST_LAUNCHES= 'REQUEST_LAUNCHES';
export const RECEIVE_LAUNCHES= 'RECEIVE_LAUNCHES';
export const REQUEST_ROCKETS= 'REQUEST_ROCKETS';
export const RECEIVE_ROCKETS= 'RECEIVE_ROCKETS';
export const SET_FILTER= 'SET_FILTER';
export const RESET_FILTER= 'RESET_FILTER';